name: Linting Python code (flake8)

on:
  push:
  pull_request:
    branches:
    - main
    - develop

permissions:
  contents: read

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["{{ cookiecutter.python_version }}", ...]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v4
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Lint with flake8
      run: |
        flake8 {{ cookiecutter.package_slug }}
