name: Linting Python code (flake8)

on:
  push:
  pull_request:
    branches:
    - main
    - develop

permissions:
  contents: read

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python {{ cookiecutter.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: '{{ cookiecutter.python_version }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Lint with flake8
      run: |
        flake8 {{ cookiecutter.package_slug }}
