name: Static typechecking (mypy)

on:
  push:
  pull_request:
    branches:
    - main
    - develop

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python {{ cookiecutter.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: '{{ cookiecutter.python_version }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Static typechecking with mypy
      uses: tsuyoshicho/action-mypy@v4
