name: Python linting (pylint)

on:
  push:
  pull_request:
    branches:
    - main
    - develop

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["{{ cookiecutter.python_version }}", ...]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v4
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=9 --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**" ! -path "**/tests/**")
