name: Python tests (pytest)

on:
  push:
  pull_request:
    branches:
    - main
    - develop

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['{{ cookiecutter.python_version }}', ...]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v4
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Test with pytest
      run: |
        pytest --cov={{ cookiecutter.package_slug }}/ --cov-report term-missing --junitxml=report.xml tests/
        coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
