# SPDX-FileCopyrightText: {{ cookiecutter.__year }} {{ cookiecutter.author_name }}
#
# SPDX-License-Identifier: {{ cookiecutter.license }}

version = 1

[[annotations]]
SPDX-FileCopyrightText = "{{ cookiecutter.__year }} {{ cookiecutter.author_name }}"
SPDX-License-Identifier = "{{ cookiecutter.license }}"
path = "VERSION"

[[annotations]]
SPDX-FileCopyrightText = "{{ cookiecutter.__year }} {{ cookiecutter.author_name }}"
SPDX-License-Identifier = "{{ cookiecutter.license }}"
path = "{{ cookiecutter.package_slug }}/py.typed"
